from Point import Point
from constants import SPEED_OF_LIGHT, BANDWIDTH, T0, CENTERED_WAVELENGTH, CENTERED_FREQUENCY


CPI = 0.74
PLATFORM_POS = "/Users/zxiao23/Desktop/BWSISummer/team5/emulatorTest/input/PLATFORMPOS.pkl"
#RANGE_RESOLUTION = SPEED_OF_LIGHT/(2* BANDWIDTH)
#CROSS_RANGE_RESOLUTION = CENTERED_WAVELENGTH * RANGE_TO_TARGET / (2*VELOCITY*CPI)
RANGE_RESOLUTION = 0.1
CROSS_RANGE_RESOLUTION = 0.1

SCAN_START = 0 #+/-499,998 ps
SCAN_END = int(2*26e12/SPEED_OF_LIGHT) #+/-499,998 ps
SCAN_RES = 32 #1-511
BII = 8 #6-15