# Logger configuration
name: &name 'emulator'
config:
  version: 1
  formatters:
    full:
      format: '%(asctime)s   %(module)-25s   %(levelname)-9s   %(message)s'
    brief:
      format: '%(asctime)s   %(levelname)-9s   %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: 'logging.FileHandler'
      level: 'DEBUG'
      formatter: 'brief'
      filename: *name
  loggers:
    *name:
      handlers:
        - console
        - file
      level: 'INFO' # Effective logging level
